networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/app:delegated
    depends_on:
      - laravel
    networks:
      - laravel

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app 
    restart: unless-stopped
    tty: true
    ports:
      - "9000"    
    volumes:
      - ./laravel:/var/www/app:delegated
    networks:
      - laravel
